services:
  leaderboard:
    build: .
    deploy:
      replicas: 5
    networks:
      - fognw

networks:
  fognw:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"